<#
    .SYNOPSIS
        Pull all online computers in domain's LLDP data and convert to rudimentary network diagram
    .DESCRIPTION
        Example document created for better understanding of the use of the Get-SwitchInfo tool. If no list of PCs are passed, the tool will query Active Directory and build list of online PCs, then use those to build out the map.
    .PARAMETER Computers
        An array of all of the FQDN or IP addresses of PCs on the network
        #Repeat for more than 1 parameter
    .NOTES
        Version:  1.1
        Author:  Alden Wilson
        Creation Date:  07-05-2023
        Last Update:  07-06-2023
    .EXAMPLE
        Get-NetworkMap $Computers


#>
param (
    [Parameter(ValuefromPipeline = $True)]
    $Computers
)

<############
  Script
############>

# Build out some temporary ArrayLists
[System.Collections.ArrayList]$OnlinePCs = @()
[System.Collections.ArrayList]$invalidWorkstations = @()
[System.Collections.ArrayList]$WorkingWorkstations = @()

# if no input is passed, grab all AD computers
if ($null -eq $Computers) {
    try {
        $Workstations = (Get-ADComputer -Filter *).name
    }
    catch [System.Management.Automation.CommandNotFoundException] {
        Write-Error -Message "If not passing a Workstation into this, the tool must be ran on a machine with access to the Get-ADComputer cmdlet."
        Exit 1;
    }
}
elseif ($Computers.count -eq 1) {
    Write-Error -Message "This tool is intended to be ran across multiple devices to map out the network. Please include at least two devices in your query."
}
ForEach ($Computer in $Workstations) {
    if (Test-Connection -ComputerName $Computer -Quiet -Count 1) {
        $OnlinePCs.Add($Computer) | Out-Null
    }
}
ForEach ($OnlinePC in $OnlinePCs) {
    $testSession = New-PSSession -Computer $OnlinePC
    if (-not($testSession)) {
        $invalidWorkstations.Add($OnlinePC) | out-Null
    }
    else {
        $WorkingWorkstations.Add($OnlinePC) | out-null
        Remove-PSSession $OnlinePC
    }
}
$result = (.\Get-SwitchInfo.ps1 -ComputerName $WorkingWorkstations)

<############
  Exports
############>

$parsed = $result | select-object Computer, PortDescription, @{name = "IPAddress"; Expression = { $_.IPAddress } }, ChassisID, Device, SystemDescription, @{name = "shape"; Expression = {'mxgraph.cisco.computers_and_peripherals.pc'}} | ConvertTo-Csv -Delimiter ',' -NoTypeInformation
$routers = $result | Sort-Object Device |select-object Device | Get-Unique -AsString
foreach ($router in $routers.device) {
    $parsed += '"' + $Router +'","","","","","mxgraph.cisco.switches.layer_3_switch"'
}
$CSV = @"

##Network Diagram generated by PsDrawIO
# label: %Computer%
## style: shape=%shape%;fillColor=%fill%;strokeColor=%stroke%;verticalLabelPosition=bottom;aspect=fixed;
# style: label;shape=%shape%;whiteSpace=wrap;html=1;rounded=1;fillColor=%fill%;strokeColor=%stroke%;
# namespace: csvimport-
# connect: {"from": "Device", "to": "Computer", "invert": false, "fromlabel": "PortDescription", \
#          "style": "text=%PortDescription%;curved=1;endArrow=blockThin;endFill=1;fontSize=11;"}
# width: 40
# height: 40
# ignore: id,fill,stroke,refs
# nodespacing: 20
# levelspacing: 20
# edgespacing: 20
# layout: horizontalflow
## CSV data starts below this line
"@
return $CSV, $parsed